# Generated by Django 4.2.4 on 2023-08-31 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="opt",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
