# Generated by Django 4.2.4 on 2023-08-31 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_opt"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="opt",),
        migrations.AddField(
            model_name="user",
            name="otp",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
