# Generated by Django 4.2.4 on 2023-09-05 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_field"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="field", unique_together={("user", "coordinates")},
        ),
    ]
