# Generated by Django 4.2.4 on 2023-09-05 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_field_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="field", unique_together=set(),),
    ]
